doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.0'
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: '~^(?!messenger_messages)~'
        mapping_types:
            # doctrine + postgres sometimes screws up and prefixes text with an _...
            _text: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        metadata_cache_driver:
            type: pool
            pool: doctrine.metadata_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.query_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

        mappings:
            App\Domain\Models:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mappings/models'
                prefix: 'App\Domain\Models'
                alias: App

            Somnambulist\Domain\Entities\Types:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mappings/somnambulist'
                prefix: 'Somnambulist\Domain\Entities\Types'
                alias: Somnambulist
