framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: '%env(APP_SESSION_URL)%'
        name: app_web_session
        cookie_lifetime: 0
        cookie_secure: true
        cookie_samesite: strict
        sid_bits_per_character: 5
        sid_length: 48
        gc_maxlifetime: 14400

    #esi: true
    #fragments: true
    php_errors:
        log: true
