framework:
    messenger:
        failure_transport: failed
        default_bus: command.bus

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction

            query.bus:
                middleware:
                    - validation

            event.bus:
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            domain_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/domain_events'
                serializer: somnambulist.domain.event_serializer
                options:
                    exchange:
                        name: domain_events
                        type: fanout
                        durable: true

            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            Somnambulist\Domain\Events\AbstractDomainEvent: domain_events
            Somnambulist\Domain\Commands\AbstractCommand: sync
            Somnambulist\Domain\Queries\AbstractQuery: sync
