framework:
    messenger:
        default_bus: command.bus

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        buses:
            command.bus:
                middleware:
                    - validation

            query.bus:
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            Somnambulist\Domain\Commands\AbstractCommand: sync
            Somnambulist\Domain\Queries\AbstractQuery: sync
