
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Somnambulist\Domain\Commands\CommandBus:
        alias: Somnambulist\Domain\Commands\Adapters\MessengerCommandBus
        public: true

    Somnambulist\Domain\Commands\Adapters\MessengerCommandBus:

#    Somnambulist\Domain\Events\EventBus:
#        alias: Somnambulist\Domain\Events\Adapters\MessengerEventBus
#        public: true
#
#    Somnambulist\Domain\Events\Adapters\MessengerEventBus:

    Somnambulist\Domain\Jobs\JobQueue:
        alias: Somnambulist\Domain\Jobs\Adapters\MessengerJobQueue
        public: true

    Somnambulist\Domain\Jobs\Adapters\MessengerJobQueue:

    Somnambulist\Domain\Queries\QueryBus:
        alias: Somnambulist\Domain\Queries\Adapters\MessengerQueryBus
        public: true

    Somnambulist\Domain\Queries\Adapters\MessengerQueryBus:

    Somnambulist\ApiBundle\ArgumentResolvers\:
        resource: '../../vendor/somnambulist/api-bundle/src/ArgumentResolvers/'
        tags:
            - { name: controller.argument_value_resolver, priority: 105 }
