somnambulist_api:
    exception_handler:
        converters:
            Assert\InvalidArgumentException: Somnambulist\ApiBundle\Services\Converters\AssertionExceptionConverter
            Assert\LazyAssertionException: Somnambulist\ApiBundle\Services\Converters\LazyAssertionExceptionConverter
            Symfony\Component\Messenger\Exception\HandlerFailedException: Somnambulist\ApiBundle\Services\Converters\HandlerFailedExceptionConverter
    request_handler:
        per_page: 20
        max_per_page: 100
        limit: 100
        request_id_header: 'X-Request-Id'
    subscribers:
        exception_to_json: true
        json_to_post: true
        request_id: true
