
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Somnambulist\Domain\Commands\CommandBus:
        alias: Somnambulist\Domain\Commands\Messenger\CommandBus

    Somnambulist\Domain\Commands\Messenger\CommandBus:
        public: true

    Somnambulist\Domain\Queries\QueryBus:
        alias: Somnambulist\Domain\Queries\Messenger\QueryBus

    Somnambulist\Domain\Queries\Messenger\QueryBus:
        public: true

    Somnambulist\ApiBundle\ArgumentResolvers\:
        resource: '../../vendor/somnambulist/api-bundle/src/ArgumentResolvers/'
        tags:
            - { name: controller.argument_value_resolver, priority: 105 }
