version: '3'

services:
  app:
    build:
      context: .
      dockerfile: src/Resources/docker/prod/app/Dockerfile
    networks:
      - app_network_backend

networks:
  app_network_backend:
    external: true
