version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: src/Resources/docker/test/app/Dockerfile
    depends_on:
      - postgres
    networks:
      - backend

  app-redis:
    image: redis:alpine
    networks:
      - backend

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    volumes:
      - ./src/Resources/docker/test/postgres:/docker-entrypoint-initdb.d
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmqcookienamehere
    networks:
      - backend

networks:
  backend:
    driver: bridge
