version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: src/Resources/docker/dev/app/Dockerfile
    networks:
      - app_network_backend
    labels:
      traefik.port: 8080
      traefik.frontend.rule: "Host:app.example.dev"

  app-redis:
    image: redis:alpine
    networks:
      - app_network_backend
    labels:
      traefik.enable: "false"

networks:
  app_network_backend:
    external: true
