monolog:
    handlers:
        main:
            type: syslogudp
            host: "%env(SYSLOG_HOST)%"
            port: "%env(int:SYSLOG_PORT)%"
            facility: local1
            ident: "%env(APP_SERVICE_APP)%"
            level: debug
            channels: ["!event"]
            formatter: monolog.formatter.syslog

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
            formatter: monolog.formatter.default
