
parameters:

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    #
    # Example overridden SF ApiClient to record API responses
    #
#    app.some_service.recording_api_client:
#        decorates: app.some_service.api_client
#        class: Somnambulist\ApiClient\Client\Decorators\RecordResponseDecorator
#        arguments:
#            $client: '@app.some_service.recording_api_client.inner'
#            $mode: '%env(APP_TEST_API_PLAYBACK_MODE)%'
