# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    route.requirements.id: '[0-9]+'
    route.requirements.provider: '[a-z\-\_0-9]+'
    route.requirements.slug: '[a-z\-\_0-9]+'
    route.requirements.type: '[a-z\-\_0-9]+'
    route.requirements.uuid: '([a-fA-F0-9]{8}-(?:[a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12}){1}'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Custom monolog line formatters
    #

    monolog.formatter.default:
        class: Monolog\Formatter\LineFormatter
        arguments:
            $format:                     "%%channel%%.%%level_name%%: %%message%% %%context%%\n"
            $allowInlineLineBreaks:      true
            $ignoreEmptyContextAndExtra: true

    monolog.formatter.syslog:
        class: Monolog\Formatter\LineFormatter
        arguments:
            $format:                     "[%%extra.request_id%%] %%channel%%.%%level_name%%: %%message%% %%context%%\n"
            $allowInlineLineBreaks:      true
            $ignoreEmptyContextAndExtra: true



    #
    # App Services that need container resolution
    #

    App\Delivery\Api\:
        resource: '../src/Delivery/Api'
        tags: ['controller.service_arguments']

    App\Delivery\Console\:
        resource: '../src/Delivery/Console'
        tags: ['console.command']

    App\Domain\Services\:
        resource: '../src/Domain/Services'
        public: true

    App\Application\CommandHandlers\:
        resource: '../src/Application/CommandHandlers/*'
        tags: [{ name: messenger.message_handler, bus: command.bus }]

    App\Application\QueryHandlers\:
        resource: '../src/Application/QueryHandlers/*'
        tags: [{ name: messenger.message_handler, bus: query.bus }]

    App\Infrastructure\Persistence\Repositories\:
        resource: '../src/Infrastructure/Persistence/Repositories/*'

    # Add repository interface mappings here to provide an implementation for a repository
    #App\Domain\Services\Repositories\MyModelRepository:
    #    alias:  App\Infrastructure\Persistence\Repositories\MyModelRepository
    #    public: true
